# -*- coding: utf-8 -*-
"""pedropandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mrMBlEwEObaeeAddWT-J876ZZYMbj8XR
"""

from bs4 import BeautifulSoup
import pandas as pd
from urllib.request import urlopen
from pandas.io.formats.excel import ExcelFormatter

url = 'https://portal.sistemafamasul.com.br/cotacoes-online?field_categoria_cot_tid=11&field_data_cot_value_1%5Bvalue%5D%5Bday%5D=&field_data_cot_value_1%5Bvalue%5D%5Bmonth%5D=&field_data_cot_value_1%5Bvalue%5D%5Byear%5D=&undefined=Aplicar&page=0'
html = pd.read_html(url)

response = urlopen(url)
htmls = response.read()
soup = BeautifulSoup

tabela = html[0]
type(tabela)

tabela.to_csv('tabelinha')

tabela.to_excel('export_dataframe.xlsx', index = False, header=True)

"""É TETRAAAAA É TETRAAAAAAAAAAAAA"""

htmls = htmls.decode('utf-8')

soup = BeautifulSoup(htmls, 'html.parser')
type(htmls)

a = soup.find('a', {'title': 'Ir para a última página'})

print(a)

a2 = 'https://portal.sistemafamasul.com.br' + a.get('href')

type(a2)

pages = int(a2[-2:])
print(pages)

print(a2)

tabelas = []

for i in range(pages):
    urls = urlopen('https://portal.sistemafamasul.com.br/cotacoes-online?field_categoria_cot_tid=11&field_data_cot_value_1%5Bvalue%5D%5Bday%5D=&field_data_cot_value_1%5Bvalue%5D%5Bmonth%5D=&field_data_cot_value_1%5Bvalue%5D%5Byear%5D=&undefined=Aplicar&page='+ str(i + 1))    
    htmls = pd.read_html(urls)
    tabela1 = htmls[0]
    tabelas.append(tabela1)

tabelas

type(tabelas)

type(tabelas[0])

df = pd.concat(tabelas)

df

df.to_csv('datasetfinal.csv', sep=';', index = False)

df.to_excel('export_dataframefinal.xlsx', index = False, header=True)

"""como aplicar https://portal.sistemafamasul.com.br/cotacoes-online?field_categoria_cot_tid=11&field_data_cot_value_1%5Bvalue%5D%5Bday%5D=&field_data_cot_value_1%5Bvalue%5D%5Bmonth%5D=&field_data_cot_value_1%5Bvalue%5D%5Byear%5D=&undefined=Aplicar&page=1

page=1 até page=59 ou infinito sendo que page=0 é a primeira 
(testei e funcionou)
"""